name: Add contributors
on:
  schedule:
    - cron:  '*/20 * * * *'
# push:
#   branches:
#     - master

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: '/.github/workflows/src/contributors.txt'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'
